#!/usr/bin/env fish

source "$VG_INSTALL_DIR/functions"

set $code 1

switch "$argv[1]"
    case 'build'
        docker build \
            --tag vantage/alembic \
            --file "$VG_APP_DIR/vantage/alembic/Dockerfile" \
            "$VG_APP_DIR"
        set $code $status
    case 'shell'
        docker run \
            --env-file="$VG_ENV_FILE" \
            --interactive \
            --tty \
            --volume="$VG_APP_DIR":/usr/src/app \
            --net=host \
            --name vg_alembic \
            vantage/alembic bash
        set $code $status
        docker rm vg_alembic > /dev/null ^ /dev/null
    case 'learn'
        set message (get_arg_value "$argv" '--message' '-m')
        if test -z "$message"
            echo "You must supply a message using --message '...'"
            exit 1
        end
        set message "$argv[3..-1]"
        if test -z "$VG_ALEMBIC_CONFIG"
            set --global --export VG_ALEMBIC_CONFIG "/usr/src/app/migrations/alembic.ini"
        end
        docker run \
            --env-file="$VG_ENV_FILE" \
            --volume="$VG_APP_DIR":/usr/src/app \
            --net=host \
            --rm \
            vantage/alembic alembic \
                --config "$VG_ALEMBIC_CONFIG" \
                revision --autogenerate \
                --message "$message"
    case 'apply'
        if test -z "$VG_ALEMBIC_CONFIG"
            set --global --export VG_ALEMBIC_CONFIG "/usr/src/app/migrations/alembic.ini"
        end
        docker run \
            --env-file="$VG_ENV_FILE" \
            --volume="$VG_APP_DIR":/usr/src/app \
            --net=host \
            --rm \
            vantage/alembic alembic \
                --config "$VG_ALEMBIC_CONFIG" \
                upgrade head
end

exit $code
