#!/usr/bin/env fish

switch "$argv"
    case 'summary'
        echo "  app - run the app"
    case '*'
        echo "\
app build
    Build the app's docker container
app debug
    Run the app in debug mode
app serve
    Run the app
app shell
    Drop into a bash shell inside the app's container
"
end
