#!/usr/bin/env fish

set $code 1

switch "$argv"
    case 'shell'
        docker run \
            --env-file="$VG_ENV_FILE" \
            --interactive \
            --tty \
            --volume="$VG_APP_DIR":/usr/src/app \
            --net=host \
            --name vg_app \
            vantage/app bash
        set $code $status
    case 'debug'
        docker run \
            --env-file="$VG_ENV_FILE" \
            --volume="$VG_APP_DIR":/usr/src/app \
            --net=host \
            --name vg_app \
            vantage/app
        set $code $status
    case 'serve'
        docker run \
            --env-file="$VG_ENV_FILE" \
            --volume="$VG_APP_DIR":/usr/src/app \
            --net=host \
            --name vg_app \
            vantage/app gunicorn web:app --log-file - --bind 0.0.0.0:80
        set $code $status
    case 'build'
        docker build \
            --tag vantage/app \
            --file "$VG_APP_DIR/vantage/app/Dockerfile" \
            "$VG_APP_DIR"
        set $code $status
end

docker rm vg_app > /dev/null ^ /dev/null

exit $code
