#!/usr/bin/env fish

function heroku_down
    heroku maintenance:on --app "$argv"
    heroku scale web=0 --app "$argv"
end

function heroku_up
    heroku scale web=1 --app "$argv"
    heroku maintenance:off --app "$argv"
end

switch "$argv"
    case ''
        heroku_down 'scytale'
        set DB_URL (vantage --env .env/heroku env DATABASE_URL)
        heroku pg:reset DATABASE_URL --app scytale --confirm scytale
        vantage pg restore demo.dump --url "$DB_URL"
        git push heroku master
        heroku_up 'scytale'
end
