#!/usr/bin/env fish

switch "$argv"
    case 'summary'
        echo "  test - Run the tests"
    case '*'
        echo "\
test build
    Build the test docker container
test shell
    Drop into a bash shell in the test's container
test unit
    Run all of the unit tests
"
end
