#!/usr/bin/env fish

set $code 1

cat "$VG_APP_DIR/.env/test" >> "$VG_ENV_FILE"

switch "$argv"
    case 'shell'
        docker run \
            --env-file="$VG_ENV_FILE" \
            --interactive \
            --tty \
            --volume="$VG_APP_DIR":/usr/src/app \
            --net=host \
            --name vg_test \
            vantage/test bash
        set $code $status
    case 'unit'
        docker run \
            --env-file="$VG_ENV_FILE" \
            --volume="$VG_APP_DIR":/usr/src/app \
            --net=host \
            --name vg_test \
            vantage/test py.test tests/unit
        set $code $status
    case 'build'
        docker build \
            --tag vantage/test \
            --file "$VG_APP_DIR/vantage/test/Dockerfile" \
            "$VG_APP_DIR"
        set $code $status
end

docker rm vg_test > /dev/null ^ /dev/null

exit $code
