"""Add Point

Revision ID: 71de7d079c37
Revises: e6d7560692fe
Create Date: 2016-01-03 13:26:52.977321

"""

# revision identifiers, used by Alembic.
revision = '71de7d079c37'
down_revision = 'e6d7560692fe'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # commands auto generated by Alembic - please adjust!
    op.create_table(
        'point',
        sa.Column('pid', sa.Integer(), nullable=False),
        sa.Column('score', sa.Integer(), nullable=True),
        sa.Column('reason', sa.Text(), nullable=True),
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['group_id'], ['group.gid'], ),
        sa.PrimaryKeyConstraint('pid'))
    # end Alembic commands


def downgrade():
    # commands auto generated by Alembic - please adjust!
    op.drop_table('point')
    # end Alembic commands
