"""Attach points to messages

Revision ID: 97ed51c21f0e
Revises: 71de7d079c37
Create Date: 2018-01-06 20:25:48.314899

"""

# revision identifiers, used by Alembic.
revision = '97ed51c21f0e'
down_revision = '71de7d079c37'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point', sa.Column('message_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'point', 'message', ['message_id'], ['mid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'point', type_='foreignkey')
    op.drop_column('point', 'message_id')
    # ### end Alembic commands ###
