"""Add sent_at to message

Revision ID: c165aa92784b
Revises: 97ed51c21f0e
Create Date: 2018-01-06 22:02:06.452780

"""

# revision identifiers, used by Alembic.
revision = 'c165aa92784b'
down_revision = '97ed51c21f0e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('sent_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'sent_at')
    # ### end Alembic commands ###
