"""Add Message

Revision ID: e6d7560692fe
Revises: 40449c25c57a
Create Date: 2016-01-03 00:55:32.448315

"""

# revision identifiers, used by Alembic.
revision = 'e6d7560692fe'
down_revision = '40449c25c57a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # commands auto generated by Alembic - please adjust!
    op.create_table(
        'message',
        sa.Column('mid', sa.Integer(), nullable=False),
        sa.Column('cipher', sa.Text(), nullable=True),
        sa.Column('key', sa.Text(), nullable=True),
        sa.Column('plaintext', sa.Text(), nullable=True),
        sa.Column('ciphertext', sa.Text(), nullable=True),
        sa.Column('group_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['group_id'], ['group.gid'], ),
        sa.PrimaryKeyConstraint('mid'))
    # end Alembic commands


def downgrade():
    # commands auto generated by Alembic - please adjust!
    op.drop_table('message')
    # end Alembic commands
