#!/bin/bash
set -e

docker run \
    --env-file="$VG_ENV_FILE" \
    --volume="$VG_APP_DIR":/usr/src/app \
    --rm \
    scytale alembic \
        --config /usr/src/app/migrations/alembic.ini \
        upgrade head
